[package]
name = "cake-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
bitcode = { version = "0.6.0", features = ["serde"] }
candle-core = "0.6.0"

clap = { version = "4.5.8", features = ["derive"] }
hf-hub = "0.3.2"
human_bytes = "0.4.3"
lazy_static = "1.5.0"
log = "0.4.22"
memmap2 = "0.9.4"
memory-stats = "1.2.0"
regex = "1.10.5"
safetensors = "0.4.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
serde_yaml = "0.9.34"
tokenizers = { version = "0.19.1", features = ["onig"] }
tokio = { version = "1.38.0", features = ["full"] }
yoke = { version = "0.7.4", features = ["derive"] }

# Metal acceleration on macOS
[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { version = "0.6.0", features = ["metal"] }
candle-nn = { version = "0.6.0", features = ["metal"] }
candle-transformers = { version = "0.6.0", features = ["metal"] }

[target.'cfg(target_os = "ios")'.dependencies]
# https://github.com/huggingface/candle/issues/2322
# https://github.com/huggingface/candle/issues/1841
# candle-core = { version = "0.6.0", features = ["metal"] }
# candle-nn = { version = "0.6.0", features = ["metal"] }
# candle-transformers = { version = "0.6.0", features = ["metal"] }
candle-core = { version = "0.6.0" }
candle-nn = { version = "0.6.0" }
candle-transformers = { version = "0.6.0" }

# CUDA on everything else.
[target.'cfg(not(any(target_os = "macos", target_os = "ios")))'.dependencies]
candle-core = { version = "0.6.0", features = ["cuda"] }
candle-nn = { version = "0.6.0", features = ["cuda"] }
candle-transformers = { version = "0.6.0", features = ["cuda"] }
